### ISSUE TITLE
ゲーム終了後、ボタンを押しても何も起こらない

### ISSUE THREAD

**Issue by dsuz** [SetsunaTsuyuri/kakeagare_network_battle#65]
ゲーム終了後、以下の画面になるが、ボタンをクリックしても何も起きません。
<img width="315" alt="temp" src="https://user-images.githubusercontent.com/4126881/196074877-2e2065cf-dd6e-40db-b8af-ffdd4c4f06aa.png">

この時、Console に以下のエラーが出力されていました。

```
Some objects were not cleaned up when closing the scene. (Did you spawn new GameObjects from OnDestroy?)
The following scene GameObjects were found:
Karaki_DefeatEffect(Clone)
```

**Comment by SetsunaTsuyuri** [comment]
報告ありがとうございます。
ボタンを押した後、シーンが切り替わるよう修正されました。

Consoleのエラー文はボタンとは関係なく、OnDestroyのタイミングでゲームオブジェクトをInstantiateしていたことにより発生していました。
こちらも修正済みです。
